### PR TITLE
u3d/available support LTS (#276)

### LINKED ISSUE #276: New LTS releases not recognised
### Issue Checklist

- [x] I'm using the latest u3d version
- [x] I ran `u3d --help`
- [x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

Firstly, thanks for the great tool. We've integrated it into our Jenkins build process and it's proving extremely useful.
I have this week hit an issue...

Unity recently announced a [change to their release schedules](https://blogs.unity3d.com/2018/04/09/new-plans-for-unity-releases-introducing-the-tech-and-long-term-support-lts-streams/).
They plan to have Tech and LTS streams. The new LTS releases can currently be downloaded [from here](https://unity3d.com/unity/qa/lts-releases).

It seems u3d isn't finding these new versions.
I can't see `2017.4.1f1` or `2017.4.0f1` when running `u3d available`.

**Note:**
As a temporary workaround for anyone else with this issue, `u3d run` commands will still work with these releases if you install them manually using the folder naming conventions u3d expects.
e.g.
`Program Files/Unity_2017.4.1f1`

### PR DESCRIPTION
**Pull request by lacostej**
FIxes #276

### CODE REVIEW

**Comment by mattmurton** [comment]
Awesome stuff, thanks guys 👍

**Comment by lacostej** [comment]
@mattmurton we just merged into master. We will make a new release soon (1.0.21). 

Note that I updated the cache service to get this to work right away even for older u3d's as well. So it should work for now if you force a cache refresh, even if you don't update u3d.

**Comment by lacostej** [comment]
`u3d available -r` if you already ran `u3d available` within the last 24h

**Comment by mattmurton** [comment]
Thanks @lacostej.
I was being impatient and built from the source @ master.
I just tested again and it all looks good now, thanks.

**Pull request merged**
